"""Change difficulty_level to String

Revision ID: 23cf83858f53
Revises: 001
Create Date: 2025-10-18 22:15:46.387906

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "23cf83858f53"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("session_token", sa.String(length=500), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column(
            "active_guide_sessions",
            postgresql.ARRAY(sa.UUID()),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "expires_at > created_at", name="expires_after_creation"
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("session_token"),
    )
    op.create_table(
        "progress_trackers",
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "completed_steps", postgresql.ARRAY(sa.UUID()), nullable=False
        ),
        sa.Column("current_step_id", sa.UUID(), nullable=True),
        sa.Column(
            "remaining_steps", postgresql.ARRAY(sa.UUID()), nullable=False
        ),
        sa.Column("completion_percentage", sa.Float(), nullable=False),
        sa.Column(
            "estimated_time_remaining_minutes", sa.Integer(), nullable=False
        ),
        sa.Column("time_spent_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completion_percentage >= 0.0 AND completion_percentage <= 100.0",
            name="valid_completion_percentage",
        ),
        sa.CheckConstraint(
            "estimated_time_remaining_minutes >= 0",
            name="positive_estimated_time",
        ),
        sa.CheckConstraint(
            "last_activity_at >= started_at", name="activity_after_start"
        ),
        sa.CheckConstraint(
            "time_spent_minutes >= 0", name="positive_time_spent"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["guide_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("tracker_id"),
        sa.UniqueConstraint("session_id"),
    )
    op.alter_column(
        "step_guides",
        "difficulty_level",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="difficultylevel"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "steps",
        "step_status",
        existing_type=postgresql.ENUM(
            "active", "completed", "blocked", "alternative", name="stepstatus"
        ),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "steps",
        "step_status",
        existing_type=postgresql.ENUM(
            "active", "completed", "blocked", "alternative", name="stepstatus"
        ),
        server_default=sa.text("'active'::stepstatus"),
        existing_nullable=False,
    )
    op.alter_column(
        "step_guides",
        "difficulty_level",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="difficultylevel"
        ),
        existing_nullable=False,
    )
    op.drop_table("progress_trackers")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
